import type { Metadata } from "next";
import { ABeeZee, Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";

const montserrat = Outfit({
  variable: "--font-montserrat",
  weight: "400",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${montserrat.variable} overscroll-y-none overscroll-x-none h-screen antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
